package org.folio.util;

import io.vertx.core.Future;
import io.vertx.core.buffer.Buffer;
import io.vertx.ext.web.client.HttpResponse;
import io.vertx.ext.web.client.WebClient;
import org.folio.rest.client.TenantClient;

/**
 * @author barbaraloehle
 */
public class TenantClientGeneralized extends TenantClient {

  private final String moduleUrlLocal;
  private final String okapiUrlLocal;
  private final String tenantIdLocal;
  private final String tokenLocal;
  private final String permissionsLocal;
  private final WebClient webClientLocal;

  public TenantClientGeneralized(String moduleUrl, String okapiUrl, String tenantId, String token, String permissions,
    WebClient webClient) {
    super(okapiUrl, tenantId, token, webClient);
    this.moduleUrlLocal = moduleUrl;
    this.okapiUrlLocal = okapiUrl;
    this.tenantIdLocal = tenantId;
    this.tokenLocal = token;
    this.permissionsLocal = permissions;
    this.webClientLocal = webClient;
  }

  /**
   * Service endpoint "/_/tenant/"+operation_id+""+queryParams.toString()
   *
  */
  @Override
  public Future<HttpResponse<Buffer>> deleteTenantByOperationId(String operation_id) {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.TenantResource
    StringBuilder queryParams = new StringBuilder("?");
    io.vertx.ext.web.client.HttpRequest<Buffer> request = webClientLocal.requestAbs(io.vertx.core.http.HttpMethod.DELETE, moduleUrlLocal+"/_/tenant/"+operation_id+""+queryParams.toString());
    request.putHeader("Accept", "text/plain");
    if (tenantIdLocal!= null) {
      request.putHeader("X-Okapi-Token", tokenLocal);
      request.putHeader("x-okapi-tenant", tenantIdLocal);
     }
     if (moduleUrlLocal != null) {
      request.putHeader("X-Okapi-Module-Url", moduleUrlLocal);
    }
    if (okapiUrlLocal != null) {
      request.putHeader("X-Okapi-Url", okapiUrlLocal);
    }
    if (permissionsLocal != null) {
      request.putHeader("X-Okapi-Permissions", permissionsLocal);
    }
    return request.send();
  }

  /**
   * Service endpoint "/_/tenant/"+operation_id+""+queryParams.toString()
   *
   */
  @Override
  public Future<HttpResponse<Buffer>> getTenantByOperationId(String operation_id, int wait) {
    // Auto-generated code
    // - generated by       org.folio.rest.tools.ClientGenerator
    // - generated based on org.folio.rest.jaxrs.resource.TenantResource
    StringBuilder queryParams = new StringBuilder("?");
    queryParams.append("wait=");
    queryParams.append(wait);
    queryParams.append("&");
    io.vertx.ext.web.client.HttpRequest<Buffer> request = webClientLocal.requestAbs(io.vertx.core.http.HttpMethod.GET, moduleUrlLocal+"/_/tenant/"+operation_id+""+queryParams.toString());
    request.putHeader("Accept", "application/json,text/plain");
    if (tenantIdLocal!= null) {
      request.putHeader("X-Okapi-Token", tokenLocal);
      request.putHeader("x-okapi-tenant", tenantIdLocal);
     }
     if (moduleUrlLocal != null) {
      request.putHeader("X-Okapi-Module-Url", moduleUrlLocal);
    }
    if (okapiUrlLocal != null) {
      request.putHeader("X-Okapi-Url", okapiUrlLocal);
    }
    if (permissionsLocal != null) {
      request.putHeader("X-Okapi-Permissions", permissionsLocal);
    }
    return request.send();
  }

  /**
   * Service endpoint "/_/tenant"+queryParams.toString()
   * raml-module-builder/domain-models-runtime/target/generated-sources/raml-jaxrs/org/folio/rest/client/TenantClient.java
   */
  @Override
  public Future<HttpResponse<Buffer>> postTenant(org.folio.rest.jaxrs.model.TenantAttributes tenantAttributes) {
    StringBuilder queryParams = new StringBuilder("?");
    Buffer buffer = Buffer.buffer();
    if (tenantAttributes!= null) {
      buffer.appendString(org.folio.rest.tools.ClientHelpers.pojo2json(tenantAttributes));
    }
    io.vertx.ext.web.client.HttpRequest<Buffer> request = webClientLocal
      .requestAbs(io.vertx.core.http.HttpMethod.POST, moduleUrlLocal+"/_/tenant"+queryParams.toString());
    request.putHeader("Content-type", "application/json");
    request.putHeader("Accept", "application/json,text/plain");
    if (tenantIdLocal!= null) {
      request.putHeader("X-Okapi-Token", tokenLocal);
      request.putHeader("x-okapi-tenant", tenantIdLocal);
     }
     if (moduleUrlLocal != null) {
      request.putHeader("X-Okapi-Module-Url", moduleUrlLocal);
    }
    if (okapiUrlLocal != null) {
      request.putHeader("X-Okapi-Url", okapiUrlLocal);
    }
    if (permissionsLocal != null) {
      request.putHeader("X-Okapi-Permissions", permissionsLocal);
    }

    return request.sendBuffer(buffer);
  }
}
