FROM ghcr.io/julianladisch/simplesamlphp:1.19.8

COPY server.key      /var/www/simplesamlphp/cert/server.key
COPY server.crt      /var/www/simplesamlphp/cert/server.crt
COPY authsources.php /var/www/simplesamlphp/config/authsources.php
