FROM kenchan0130/simplesamlphp:develop

COPY server.key      /var/www/simplesamlphp/cert/server.key
COPY server.crt      /var/www/simplesamlphp/cert/server.crt
COPY authsources.php /var/www/simplesamlphp/config/authsources.php
